### ISSUE TITLE
cash account donations

### ISSUE THREAD

**Issue by emergent-reasons** [KarolTrzeszczkowski/Electron-Cash-Last-Will-Plugin#1]
Hello Karol. Love your plugin, contract, and explanation.

I noticed you have a cash account in the donation section at the bottom.

1. Maybe the registration did not work? I did not find a valid registration in that block or with that name.

2. Instead of the block, you have to subtract the block modifier of `563620` which you can see at [the top of the specification](https://gitlab.com/cash-accounts/specification/blob/master/SPECIFICATION.md). Then the number you listed would be `567890 - 563620 = 4270`. I only found one registration on `#4270` and it was an automated registration with just a number (4270#4270).

I am sure you can do it yourself but I am happy to help any time on telegram or discord.

**Comment by KarolTrzeszczkowski** [comment]
Thank you, I tried to find where have I made an error, but I couldn't so I just re-registered cash account as Licho :) Thank you for drawing my attention to this.
